# Generated by Django 5.0.7 on 2024-10-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcourse',
            name='course',
            field=models.CharField(choices=[('AOOP', 'Advanced Object-Oriented Programming'), ('PFSD', 'Python Full Stack Development'), ('OS', 'Operaing Systems'), ('AIML', 'Arificaial Intelligence and Machine Learning')], max_length=50),
        ),
    ]
